name: Main Deployment

# ==========================================================
# GITHUB ACTIONS PERMISSIONS
# ==========================================================

permissions:
  contents: read
  id-token: write

# ==========================================================
# WORKFLOW TRIGGERS
# ==========================================================

on:
  push:
    branches:
      - main

  workflow_dispatch:

# ==========================================================
# JOBS
# ==========================================================

jobs:

  # ========================================================
  # TERRAFORM + CLOUDFORMATION
  # ========================================================

  terraform:
    uses: ./.github/workflows/terraform.yml
    secrets: inherit

  # ========================================================
  # DOCKER + AMAZON ECR
  # ========================================================

  docker:
    needs:
      - terraform
    uses: ./.github/workflows/docker.yml
    secrets: inherit

  # ========================================================
  # KUBERNETES + AMAZON EKS
  # ========================================================

  kubernetes:
    needs:
      - terraform
      - docker
    uses: ./.github/workflows/kubernetes.yml
    secrets: inherit

